# Generated by Django 3.1.7 on 2021-02-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('collect_date', models.DateField(verbose_name='date collected')),
                ('related_item', models.ManyToManyField(related_name='_collecteditem_related_item_+', to='data.CollectedItem')),
            ],
        ),
    ]
