# Generated by Django 3.1.7 on 2021-02-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collecteditem',
            name='detail_text',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='collecteditem',
            name='related_item',
            field=models.ManyToManyField(blank=True, related_name='_collecteditem_related_item_+', to='data.CollectedItem'),
        ),
    ]
