# Generated by Django 3.1.7 on 2021-02-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210224_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='collecteditem',
            name='icon_image',
            field=models.ImageField(height_field=500, null=True, upload_to='', width_field=500),
        ),
    ]
