# Generated by Django 3.1.7 on 2021-02-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_collecteditem_icon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecteditem',
            name='icon_image',
            field=models.ImageField(null=True, upload_to='itemicons'),
        ),
    ]
