# Generated by Django 3.1.7 on 2021-02-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20210224_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecteditem',
            name='icon_image',
            field=models.ImageField(default='media/missing.png', upload_to='itemicons'),
        ),
    ]
